---
- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - lsb-release
      - gnupg
    state: present
    update_cache: yes

######## PostgreSQL ########
- name: Add PostgreSQL GPG key
  shell: |
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/postgresql-archive-keyring.gpg

- name: Add PostgreSQL repository
  copy:
    dest: /etc/apt/sources.list.d/pgdg.list
    content: |
      deb [signed-by=/usr/share/keyrings/postgresql-archive-keyring.gpg] http://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main

- name: Update apt cache after adding PostgreSQL repo
  apt:
    update_cache: yes

- name: Install PostgreSQL 14
  apt:
    name: postgresql-14
    state: present

######## Redis ########
- name: Install Redis (from official Ubuntu repo)
  apt:
    name: redis-server
    state: present

######## RabbitMQ + Erlang ########
- name: Add RabbitMQ Erlang GPG key
  shell: |
    curl -fsSL https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.key | gpg --dearmor -o /usr/share/keyrings/rabbitmq-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/rabbitmq-archive-keyring.gpg

- name: Add RabbitMQ Erlang repository
  copy:
    dest: /etc/apt/sources.list.d/rabbitmq-erlang.list
    content: |
      deb [signed-by=/usr/share/keyrings/rabbitmq-archive-keyring.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ ansible_lsb.codename }} main

- name: Add RabbitMQ server GPG key
  shell: |
    curl -fsSL https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.key | gpg --dearmor -o /usr/share/keyrings/rabbitmq-server-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/rabbitmq-server-archive-keyring.gpg

- name: Add RabbitMQ server repository
  copy:
    dest: /etc/apt/sources.list.d/rabbitmq-server.list
    content: |
      deb [signed-by=/usr/share/keyrings/rabbitmq-server-archive-keyring.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu {{ ansible_lsb.codename }} main

- name: Update apt cache after adding RabbitMQ repos
  apt:
    update_cache: yes

- name: Wait for apt lock to be released
  ansible.builtin.shell: |
    while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || \
          fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do
      echo "Waiting for other package managers to finish..."
      sleep 50
    done
  changed_when: false

- name: Install Erlang and RabbitMQ
  apt:
    name:
      - erlang
      - rabbitmq-server
    state: present

######## Nginx ########
- name: Install Nginx
  apt:
    name: nginx
    state: present

######## Docker ########
- name: Remove old Docker versions
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker.io
      - docker-doc
      - docker-compose
    state: absent
    purge: yes

- name: Remove Docker data directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/docker
    - /var/lib/containerd

- name: Add Docker's official GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes

- name: Install Docker Engine
  apt:
    name:
      - docker.io
      - docker-buildx
      - docker-compose
    state: present
